import type { D1DatabaseLike } from "./repository.ts";
import { resolveNovelIdentity } from "./repository.ts";
import { hrefChapter } from "./params.ts";
import {
  atlasKindFromMetadata,
  type AtlasArc,
  type AtlasChapterBoundary,
  type AtlasCharacteristic,
  type AtlasData,
  type AtlasEdge,
  type AtlasNode,
  type AtlasScope,
} from "./atlas.ts";

interface ChapterRow { chapter_number: number; title: string }

const safeJsonStrings = (value: string): string[] => {
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : [];
  } catch {
    return [];
  }
};

function readableJson(value: unknown): string {
  const source = typeof value === "string" ? value : "";
  if (!source.trim() || source.trim() === "{}" || source.trim() === "[]") return "";
  try {
    const parsed = JSON.parse(source);
    if (Array.isArray(parsed)) return parsed.map(String).filter(Boolean).join(", ");
    if (parsed && typeof parsed === "object") {
      return Object.entries(parsed as Record<string, unknown>)
        .filter(([, item]) => item !== "" && item !== null && item !== undefined)
        .map(([key, item]) => `${key.replaceAll("_", " ")}: ${Array.isArray(item) ? item.join(", ") : String(item)}`)
        .join("\n");
    }
    return String(parsed);
  } catch {
    return source;
  }
}

const sourceRef = (novelId: string, chapterNumber: number, label = "") => ({
  chapterId: String(chapterNumber),
  href: chapterNumber > 0 ? hrefChapter(novelId, String(chapterNumber)) : "",
  label: label || (chapterNumber > 0 ? `Chapter ${chapterNumber}` : "Stored metadata"),
});

function chapterBoundary(row: ChapterRow): AtlasChapterBoundary {
  return {
    chapterId: String(Number(row.chapter_number)),
    ordinal: Number(row.chapter_number),
    title: row.title || `Chapter ${Number(row.chapter_number)}`,
    reviewed: true,
  };
}

async function getBoundary(db: D1DatabaseLike, novelId: string, langId: string, chapterId: string) {
  const number = Number.parseInt(chapterId, 10);
  if (!Number.isInteger(number) || number < 1) return null;
  return db.prepare(`
    SELECT chapter_number, COALESCE(NULLIF(chapter_title, ''), 'Chapter ' || chapter_number) AS title
    FROM chapters
    WHERE novel_id = ? AND lang_id = ? AND chapter_number = ? AND stale = 0 AND status = 'completed'
    LIMIT 1
  `).bind(novelId, langId, number).first<ChapterRow>();
}

async function firstBoundary(db: D1DatabaseLike, novelId: string, langId: string) {
  return db.prepare(`
    SELECT chapter_number, COALESCE(NULLIF(chapter_title, ''), 'Chapter ' || chapter_number) AS title
    FROM chapters
    WHERE novel_id = ? AND lang_id = ? AND stale = 0 AND status = 'completed'
    ORDER BY chapter_number ASC LIMIT 1
  `).bind(novelId, langId).first<ChapterRow>();
}

export async function listAtlasChapters(db: D1DatabaseLike, routeNovelId: string): Promise<{ version: number; coverageNote: string; chapters: AtlasChapterBoundary[] } | null> {
  const identity = await resolveNovelIdentity(db, routeNovelId);
  if (!identity) return null;
  const [{ results }, versionRow] = await Promise.all([
    db.prepare(`
      SELECT chapter_number, COALESCE(NULLIF(chapter_title, ''), 'Chapter ' || chapter_number) AS title
      FROM chapters
      WHERE novel_id = ? AND lang_id = ? AND stale = 0 AND status = 'completed'
      ORDER BY chapter_number ASC
    `).bind(identity.novelId, identity.langId).all<ChapterRow>(),
    db.prepare(`SELECT COALESCE(MAX(rowid), 1) AS version FROM translation_runs WHERE novel_id = ? AND lang_id = ?`)
      .bind(identity.novelId, identity.langId).first<{ version: number }>(),
  ]);
  if (!results.length) return null;
  return {
    version: Number(versionRow?.version ?? 1),
    coverageNote: "Structured metadata generated by the local sequential translation pipeline.",
    chapters: results.map(chapterBoundary),
  };
}

export interface AtlasLoadOptions {
  fromChapterId?: string;
  throughChapterId: string;
  scope?: AtlasScope;
  includeUnreviewed?: boolean;
}

export async function loadAtlasData(db: D1DatabaseLike, routeNovelId: string, options: AtlasLoadOptions | string): Promise<AtlasData | null> {
  const normalized: AtlasLoadOptions = typeof options === "string"
    ? { throughChapterId: options, scope: "through", includeUnreviewed: false }
    : options;
  const identity = await resolveNovelIdentity(db, routeNovelId);
  if (!identity) return null;

  const throughRow = await getBoundary(db, identity.novelId, identity.langId, normalized.throughChapterId);
  if (!throughRow) return null;
  const fromRow = normalized.fromChapterId
    ? await getBoundary(db, identity.novelId, identity.langId, normalized.fromChapterId)
    : await firstBoundary(db, identity.novelId, identity.langId);
  if (!fromRow) return null;

  const from = chapterBoundary(fromRow);
  const through = chapterBoundary(throughRow);
  if (from.ordinal > through.ordinal) return null;
  const scope = normalized.scope ?? "through";
  const windowStart = scope === "through" ? 1 : from.ordinal;
  const dataEnd = through.ordinal;

  const [nodeRows, edgeRows, arcRows, versionRow] = await Promise.all([
    db.prepare(`
      WITH valid AS (
        SELECT e.*
        FROM entities e
        JOIN chapters c ON c.novel_id=e.novel_id AND c.lang_id=e.lang_id AND c.chapter_number=e.chapter_number
        WHERE e.novel_id=? AND e.lang_id=? AND e.chapter_number<=? AND c.stale=0 AND c.status='completed'
      ), latest AS (
        SELECT entity_id, MAX(chapter_number) AS chapter_number FROM valid GROUP BY entity_id
      )
      SELECT e.entity_id, e.entity_type, e.source_name, e.canonical_name, e.aliases_json,
             e.description, e.biography_json, e.appearance_json, e.behavior_json, e.characteristics_json,
             COALESCE(e.first_seen_chapter, (SELECT MIN(v2.chapter_number) FROM valid v2 WHERE v2.entity_id=e.entity_id), e.chapter_number) AS first_seen,
             e.chapter_number AS profile_through
      FROM valid e JOIN latest l ON l.entity_id=e.entity_id AND l.chapter_number=e.chapter_number
      ORDER BY first_seen ASC, e.entity_type, e.canonical_name COLLATE NOCASE
    `).bind(identity.novelId, identity.langId, dataEnd).all<Record<string, unknown>>(),
    db.prepare(`
      WITH valid AS (
        SELECT r.*
        FROM relationships r
        JOIN chapters c ON c.novel_id=r.novel_id AND c.lang_id=r.lang_id AND c.chapter_number=r.chapter_number
        WHERE r.novel_id=? AND r.lang_id=? AND r.chapter_number<=? AND c.stale=0 AND c.status='completed'
      ), timeline AS (
        SELECT valid.*,
               LEAD(chapter_number) OVER (PARTITION BY relationship_id ORDER BY chapter_number) AS next_chapter
        FROM valid
      )
      SELECT * FROM timeline
      WHERE chapter_number <= ? AND COALESCE(next_chapter - 1, 2147483647) >= ?
      ORDER BY chapter_number ASC, relationship_id
    `).bind(identity.novelId, identity.langId, dataEnd, dataEnd, windowStart).all<Record<string, unknown>>(),
    db.prepare(`
      WITH valid AS (
        SELECT a.*
        FROM arcs a
        JOIN chapters c ON c.novel_id=a.novel_id AND c.lang_id=a.lang_id AND c.chapter_number=a.chapter_number
        WHERE a.novel_id=? AND a.lang_id=? AND a.chapter_number<=? AND c.stale=0 AND c.status='completed'
      ), latest AS (
        SELECT arc_id, MAX(chapter_number) AS chapter_number FROM valid GROUP BY arc_id
      ), firsts AS (
        SELECT arc_id, MIN(chapter_number) AS first_snapshot FROM valid GROUP BY arc_id
      )
      SELECT a.*, f.first_snapshot
      FROM valid a JOIN latest l ON l.arc_id=a.arc_id AND l.chapter_number=a.chapter_number
      JOIN firsts f ON f.arc_id=a.arc_id
      ORDER BY COALESCE(a.start_chapter, f.first_snapshot), a.name COLLATE NOCASE
    `).bind(identity.novelId, identity.langId, dataEnd).all<Record<string, unknown>>(),
    db.prepare(`SELECT COALESCE(MAX(rowid), 1) AS version FROM translation_runs WHERE novel_id=? AND lang_id=?`)
      .bind(identity.novelId, identity.langId).first<{ version: number }>(),
  ]);

  const nodes: AtlasNode[] = nodeRows.results.map((row) => {
    const visibleFrom = Number(row.first_seen) || 1;
    const aliases = safeJsonStrings(String(row.aliases_json ?? "[]"));
    const description = String(row.description ?? "").trim()
      || readableJson(row.biography_json)
      || readableJson(row.characteristics_json);
    return {
      id: String(row.entity_id),
      label: String(row.canonical_name || row.source_name || row.entity_id),
      kind: atlasKindFromMetadata(String(row.entity_type ?? "other")),
      entityType: String(row.entity_type ?? ""),
      description,
      aliases,
      visibleFrom,
      status: "active",
      source: sourceRef(identity.routeNovelId, visibleFrom),
      reviewed: true,
    };
  });

  const nodeIds = new Set(nodes.map((node) => node.id));
  const edges: AtlasEdge[] = edgeRows.results
    .filter((row) => nodeIds.has(String(row.source_entity_id)) && nodeIds.has(String(row.target_entity_id)))
    .map((row) => {
      const chapter = Number(row.chapter_number);
      const next = row.next_chapter == null ? null : Number(row.next_chapter);
      return {
        id: `${String(row.relationship_id)}@${chapter}`,
        source: String(row.source_entity_id),
        target: String(row.target_entity_id),
        relation: String(row.name || "related_to"),
        label: String(row.name || "Related"),
        evidence: String(row.description ?? ""),
        visibleFrom: chapter,
        validFrom: chapter,
        validTo: next ? next - 1 : null,
        status: String(row.status ?? "active"),
        certainty: "recorded",
        sourceRef: sourceRef(identity.routeNovelId, chapter),
        reviewed: true,
      };
    });

  const arcs: AtlasArc[] = arcRows.results.map((row) => {
    const firstSnapshot = Number(row.first_snapshot) || Number(row.chapter_number) || 1;
    const startChapter = row.start_chapter == null ? firstSnapshot : Number(row.start_chapter);
    const endChapter = row.end_chapter == null ? null : Number(row.end_chapter);
    return {
      id: String(row.arc_id),
      title: String(row.name || row.arc_id),
      parentArcId: "",
      startChapter,
      endChapter,
      visibleFrom: firstSnapshot,
      cycleIds: [],
      status: String(row.status ?? "active"),
      summary: String(row.summary ?? ""),
      keyEntityIds: [],
      keyEventIds: [],
      evidence: String(row.chapter_role ?? ""),
      source: sourceRef(identity.routeNovelId, Number(row.chapter_number) || firstSnapshot),
      reviewed: true,
    };
  });

  const characteristics: AtlasCharacteristic[] = nodeRows.results.map((row) => {
    const entityId = String(row.entity_id);
    const firstSeen = Number(row.first_seen) || null;
    const profileThrough = Number(row.profile_through) || null;
    return {
      entityId,
      profileKind: "detailed",
      entityType: String(row.entity_type ?? ""),
      canonicalName: String(row.canonical_name || row.source_name || entityId),
      firstSeen,
      profileThrough,
      physicalForm: readableJson(row.appearance_json),
      temperamentOrProperties: readableJson(row.behavior_json),
      abilitiesOrRole: readableJson(row.characteristics_json),
      relationshipsStatus: "",
      characteristicAsOf: readableJson(row.biography_json) || String(row.description ?? ""),
      scope: `Through chapter ${profileThrough ?? dataEnd}`,
      evidence: String(row.description ?? ""),
      reviewed: true,
    };
  });

  return {
    novelId: identity.routeNovelId,
    version: Number(versionRow?.version ?? 1),
    coverageNote: "Local SQLite metadata from the sequential translator. Completed, non-stale chapter snapshots are treated as committed reader metadata.",
    scope,
    from,
    through,
    reviewedThrough: through,
    coverageLimited: false,
    unreviewedUnlocked: false,
    nodes,
    edges,
    facts: [],
    states: [],
    events: [],
    scenes: [],
    arcs,
    cycles: [],
    characteristics,
    integrityIssueCount: 0,
  };
}

export async function loadInlineLookup(db: D1DatabaseLike, novelId: string, chapterId: string) {
  const atlas = await loadAtlasData(db, novelId, { throughChapterId: chapterId, scope: "through", includeUnreviewed: false });
  if (!atlas) return null;
  const detailedProfiles = new Map(
    atlas.characteristics
      .filter((profile) => profile.profileKind === "detailed")
      .map((profile) => [profile.entityId, profile]),
  );
  const entries = atlas.nodes.map((node) => {
    const profile = detailedProfiles.get(node.id);
    if (!profile) return node;
    const safeSummary = profile.abilitiesOrRole || profile.temperamentOrProperties || profile.characteristicAsOf;
    return safeSummary ? { ...node, description: safeSummary } : node;
  });
  return {
    version: atlas.version,
    through: atlas.through,
    reviewedThrough: atlas.reviewedThrough,
    coverageLimited: atlas.coverageLimited,
    coverageNote: atlas.coverageNote,
    entries,
  };
}

export async function loadChapterContext(db: D1DatabaseLike, novelId: string, chapterId: string) {
  const atlas = await loadAtlasData(db, novelId, {
    fromChapterId: chapterId,
    throughChapterId: chapterId,
    scope: "range",
    includeUnreviewed: false,
  });
  if (!atlas) return null;
  const ordinal = atlas.through.ordinal;
  const relationships = atlas.edges.filter((edge) => edge.visibleFrom === ordinal);
  const entityIds = new Set<string>();
  for (const edge of relationships) {
    entityIds.add(edge.source);
    entityIds.add(edge.target);
  }
  for (const node of atlas.nodes) if (node.visibleFrom === ordinal) entityIds.add(node.id);
  return {
    chapter: atlas.through,
    entities: atlas.nodes.filter((node) => entityIds.has(node.id)),
    relationships,
    facts: [],
    states: [],
    events: [],
    scenes: [],
  };
}
