from __future__ import annotations

from typing import Any, Protocol


class PreviewRepository(Protocol):
    def preview_overview(self) -> dict[str, Any]: ...
    def preview_novel(self, novel_id: str, lang_id: str) -> dict[str, Any]: ...
    def preview_chapter(self, novel_id: str, lang_id: str, chapter_number: int) -> dict[str, Any] | None: ...
    def preview_entities(self, novel_id: str, lang_id: str) -> list[dict[str, Any]]: ...
    def preview_relationships(self, novel_id: str, lang_id: str) -> list[dict[str, Any]]: ...
    def preview_terminology(self, novel_id: str, lang_id: str) -> list[dict[str, Any]]: ...
    def preview_glossary(self, novel_id: str, lang_id: str) -> list[dict[str, Any]]: ...
    def preview_arcs(self, novel_id: str, lang_id: str) -> list[dict[str, Any]]: ...
    def preview_runs(self, novel_id: str, lang_id: str, limit: int = 30) -> list[dict[str, Any]]: ...
